// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-A-HbyOpY0k2uLQCRkZWCzvfONbSW7J4',
    appId: '1:810731812897:web:34d4490afb246b8eeb4b60',
    messagingSenderId: '810731812897',
    projectId: 'cryptobase-c99a1',
    authDomain: 'cryptobase-c99a1.firebaseapp.com',
    storageBucket: 'cryptobase-c99a1.appspot.com',
    measurementId: 'G-XNHEZ1HP5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOxdjZh8GysCxFPtCyT9-ISheKkmmPj4',
    appId: '1:810731812897:android:5234306eb80376c9eb4b60',
    messagingSenderId: '810731812897',
    projectId: 'cryptobase-c99a1',
    storageBucket: 'cryptobase-c99a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRwJUHOwd_vDXDZO_zQojbnmBVX6ZUZyg',
    appId: '1:810731812897:ios:cfd39ba90f43e310eb4b60',
    messagingSenderId: '810731812897',
    projectId: 'cryptobase-c99a1',
    storageBucket: 'cryptobase-c99a1.appspot.com',
    iosClientId: '810731812897-lt8u42ns19q7smtlrklgagc2omc77tpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptobase',
  );
}
